
services:

  engine:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"

    restart: unless-stopped

  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit

    ports:
      - "8501:8501"

    depends_on:
      - engine

    environment:
      - API_BASE=http://engine:8000

    restart: unless-stopped